### ISSUE TITLE
exec the postcli error on ubuntu 

### ISSUE THREAD

**Issue by e665107** [spacemeshos/post#244]
Hi, 
when i exec the following cmd, it shows me error as follow:
./postcli -provider=0 -numUnits 18 -commitmentAtxId=813a3a65d6a2efe2909617d7dd301f3e4bc2623d194841c0627ba76cf958cfb16da64bea204b68bc6579e2c73f60b5d40ff1  -fromFile=0 -toFile=5 -datadir=/mnt/spacemesh/post_data

error:

2023-10-14T12:32:16.378Z        INFO    initialization started  {"datadir": "/mnt/spacemesh/post_data", "numUnits": 18, "maxFileSize": 4294967296, "labelsPerUnit": 4294967296}                                               
2023-10-14T12:32:16.379Z        INFO    initialization file layout      {"labelsPerFile": 268435456, "labelsLastFile": 268435456, "firstFileIndex": 0, "lastFileIndex": 5}                                                            
2023-10-14T12:32:16.381Z        INFO    initialization: starting to write file  {"fileIndex": 0, "currentNumLabels": 0, "targetNumLabels": 268435456, "startPosition": 0}                                                                     
2023-10-14T12:32:26.382Z        ERROR   error creating initializer: OclCoreError(ApiWrapper(GetPlatformIdsPlatformListUnavailable(10))) {"module": "post::initialization", "file": "ffi/src/initialization.rs", "line": 163}                                                                          
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x5863d8]

goroutine 1 [running]:
github.com/spacemeshos/post/internal/postrs.(*Scrypt).Close(0x10?)
        /home/post/internal/postrs/api.go:154 +0x18
github.com/spacemeshos/post/oracle.(*LazyScrypter).Close(0x0?)
        /home/post/oracle/oracle.go:155 +0x2c
github.com/spacemeshos/post/oracle.(*WorkOracle).Close(0x400011e198)
        /home/post/oracle/oracle.go:206 +0x34
github.com/spacemeshos/post/initialization.(*Initializer).Initialize(0x4000120000, {0x65cd00, 0x4000092700})
        /home/post/initialization/initialization.go:342 +0xb78
main.main()
        /home/post/cmd/postcli/main.go:263 +0x99c

And where the problem is? Can you help me?

**Comment by fasmat** [comment]
What output do you get if you run `./postcli -printProviders`?

**Comment by e665107** [comment]
]0;root@c59603765c65: /home/workroot@c59603765c65:/home/work# ./postcli -prin
tProviders                                                                   

2023/10/16 12:27:45 failed to get OpenCL providers failed to fetch providers
]0;root@c59603765c65: /home/workroot@c59603765c65:/home/work#

**Comment by e665107** [comment]
]0;root@c59603765c65: /home/workroot@c59603765c65:/home/work# clinfo
Number of platforms                               0
]0;root@c59603765c65: /home/workroot@c59603765c65:/home/work# 
Hope these logs can supply more infomation!

**Comment by fasmat** [comment]
From the logs I would say you don't have OpenCL setup completely on the system you are running `postcli` - otherwise Number of platforms would be at least 1.

How to setup OpenCL depends on the OS and graphics card you are using. Since you already have `clinfo` I assume you are missing some drivers for your graphics card.

**Comment by fasmat** [comment]
Since this appears to not be a problem with `postcli` I'll close this issue.

**Comment by e665107** [comment]
Thanks a lot!
