### ISSUE TITLE
Panic: runtime error: invalid memory address or nil pointer dereference (initialization.(*Initializer).NumLabelsWritten(...))

### ISSUE THREAD

**Issue by maparr** [spacemeshos/post#97]
For more information please check logs here: 
Sentry Issue on Windows: [SMAPP-14S](https://sentry.io/organizations/spacemesh/issues/3853995497/?referrer=github_integration)
Sentry issue on Linux  Sentry issue: [SMAPP-15D](https://sentry.io/organizations/spacemesh/issues/3858904140/?referrer=github_integration)
 
```
2023-01-06T10:51:05.417-0800	WARN	d898e.hare         	missed hare window, skipping layer	{"node_id": "d898e00cca6e1549a760df69947bc63c544313f30f8800e1ed0f48e5f9c7d160", "module": "hare", "layer_id": 5530, "name": "hare"}
	2023-01-06T10:51:05.417-0800	INFO	00000.defaultLogger	starting new grpc server with 7 registered service(s)
	2023-01-06T10:51:05.417-0800	INFO	app started
	2023-01-06T10:51:05.417-0800	INFO	00000.defaultLogger	starting new grpc server on :9092
	2023-01-06T10:51:06.256-0800	INFO	00000.defaultLogger	GRPC MeshService.CurrentLayer
	2023-01-06T10:51:06.261-0800	INFO	00000.defaultLogger	GRPC GlobalStateService.AccountDataQuery
	2023-01-06T10:51:06.268-0800	INFO	00000.defaultLogger	GRPC NodeService.Status
	2023-01-06T10:51:06.270-0800	INFO	00000.defaultLogger	GRPC SmesherService.SmesherID
	2023-01-06T10:51:06.297-0800	INFO	00000.defaultLogger	GRPC NodeService.Echo
	2023-01-06T10:51:06.299-0800	INFO	00000.defaultLogger	GRPC NodeService.Status
	2023-01-06T10:51:06.301-0800	INFO	00000.defaultLogger	GRPC NodeService.StatusStream
	2023-01-06T10:51:06.301-0800	INFO	00000.defaultLogger	GRPC NodeService.ErrorStream
	2023-01-06T10:51:06.304-0800	INFO	00000.defaultLogger	GRPC SmesherService.PostSetupStatus
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0x107b105]
	
	goroutine 272 [running]:
	github.com/spacemeshos/post/initialization.(*Initializer).NumLabelsWritten(...)
		/home/runner/go/pkg/mod/github.com/spacemeshos/post@v0.2.4/initialization/initialization.go:302
	github.com/spacemeshos/go-spacemesh/activation.(*PostSetupManager).Status(0xc0003e2480)
		/home/runner/work/go-spacemesh/go-spacemesh/activation/post.go:114 +0xa5
	github.com/spacemeshos/go-spacemesh/api/grpcserver.SmesherService.PostSetupStatus({{0x1b7b210, 0xc0003e2480}, {0x1b7f400, 0xc001258d20}, 0x3b9aca00}, {0xc0013f2510, 0xf}, 0x1c)
		/home/runner/work/go-spacemesh/go-spacemesh/api/grpcserver/smesher_service.go:173 +0x59
	github.com/spacemeshos/api/release/go/spacemesh/v1._SmesherService_PostSetupStatus_Handler.func1({0x1b7a138, 0xc000472c90}, {0x157a960?, 0xc000472c00})
		/home/runner/go/pkg/mod/github.com/spacemeshos/api/release/go@v1.5.3/spacemesh/v1/smesher.pb.go:646 +0x78
	github.com/grpc-ecosystem/go-grpc-middleware/logging/zap.UnaryServerInterceptor.func1({0x1b7a138, 0xc000472c60}, {0x157a960, 0xc000472c00}, 0xc000946680, 0xc000111758)
		/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/logging/zap/server_interceptors.go:31 +0x115
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1b7a138?, 0xc000472c60?}, {0x157a960?, 0xc000472c00?})
		/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
	github.com/grpc-ecosystem/go-grpc-middleware/tags.UnaryServerInterceptor.func1({0x1b7a138?, 0xc000472bd0?}, {0x157a960, 0xc000472c00}, 0xc000946680, 0xc0009466a0)
		/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/tags/interceptors.go:23 +0xa6
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1({0x1b7a138?, 0xc000472bd0?}, {0x157a960?, 0xc000472c00?})
		/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:25 +0x3a
	github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1({0x1b7a138, 0xc000472bd0}, {0x157a960, 0xc000472c00}, 0xc001569a20?, 0x14e7420?)
		/home/runner/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/chain.go:34 +0xbe
	github.com/spacemeshos/api/release/go/spacemesh/v1._SmesherService_PostSetupStatus_Handler({0x167b2a0?, 0xc001431530}, {0x1b7a138, 0xc000472bd0}, 0xc00027b030, 0xc001431050)
		/home/runner/go/pkg/mod/github.com/spacemeshos/api/release/go@v1.5.3/spacemesh/v1/smesher.pb.go:648 +0x138
	google.golang.org/grpc.(*Server).processUnaryRPC(0xc0017a63c0, {0x1b846a0, 0xc000007d40}, 0xc000f17200, 0xc0014315c0, 0x252c3b8, 0x0)
		/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
	google.golang.org/grpc.(*Server).handleStream(0xc0017a63c0, {0x1b846a0, 0xc000007d40}, 0xc000f17200, 0x0)
		/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
	google.golang.org/grpc.(*Server).serveStreams.func1.2()
		/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:965 +0x98
	created by google.golang.org/grpc.(*Server).serveStreams.func1
		/home/runner/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:963 +0x28a
	2023-01-06T10:59:55.009-0800	INFO	00000.defaultLogger	App version: v0.2.20-beta.0. Git: 8c5a399 - 8c5a3991491b3663973766942d1b7e06fc194af8 . Go Version: go1.19.4. OS: linux-amd64 
	2023-01-06T10:59:55.009-0800	INFO	00000.defaultLogger	Welcome to Spacemesh. Spacemesh full node is starting...```

**Comment by pigmej** [comment]
I had the same issue but then deleted the spacemesh data and after cleaning it the issue does not occur again.

**Comment by fasmat** [comment]
```
goroutine 272 [running]:
	github.com/spacemeshos/post/initialization.(*Initializer).NumLabelsWritten(...)
		/home/runner/go/pkg/mod/github.com/spacemeshos/post@v0.2.4/initialization/initialization.go:302
```

indicates to me that version `v0.2.4` of post is used? The current version is `v0.3.0` and should not be affected by this bug (the whole file `initialization.go` has basically been re-written between the two versions)

**Comment by fasmat** [comment]
> For more information please check logs here:
> Sentry Issue on Windows: [SMAPP-14S](https://sentry.io/organizations/spacemesh/issues/3853995497/?referrer=github_integration)
> Sentry issue on Linux Sentry issue: [SMAPP-15D](https://sentry.io/organizations/spacemesh/issues/3858904140/?referrer=github_integration)

Those links don't work for me?

**Comment by fasmat** [comment]
The Initializer has been rewritten in large parts since this issue has been reported and a significant amount of the code as moved to https://github.com/spacemeshos/post-rs.

I'm closing the issue, feel free to re-open it should the same or a similar error occur again.
